### PR TITLE
Changes to avoid errors

### PR DESCRIPTION
**Pull request by thehabes**
.env file is
```
#RERUM API access keys
refresh_token=
access_token=


# API URLS (for RERUM instance)
RERUM_REGISTRATION_URL=http://localhost:3000/v1
RERUM_API_ADDR=http://localhost:3000/v1/api/
RERUM_ID_PATTERN=http://localhost:3000/v1/id
RERUM_ACCESS_TOKEN_URL=http://localhost:3000/v1/api/accessToken

CREATE=create
UPDATE=update
DELETE=delete
QUERY=query
SET=set
UNSET=unset

#Make this value true if you plan to use this as a public API.
open_api_cors=true
```

### CODE REVIEW

**Comment by thehabes** [comment]
.env needs
```
CREATE=create
UPDATE=update
DELETE=delete
QUERY=query
SET=set
UNSET=unset
```

Vars like `{$var}/api` in .env file threw error

```javascript
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Object.exports.default (E:\tinyNode\node_modules\got\dist\source\core\utils\options-to-url.js:35:17)
    at normalizeArguments (E:\tinyNode\node_modules\got\dist\source\core\index.js:486:51)
    at got (E:\tinyNode\node_modules\got\dist\source\create.js:112:39)
    at Function.got.<computed> [as post] (E:\tinyNode\node_modules\got\dist\source\create.js:224:42)
    at E:\tinyNode\routes\create.js:21:30
    at Layer.handle [as handle_request] (E:\tinyNode\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\tinyNode\node_modules\express\lib\router\route.js:137:13) {
  input: '${RERUM_REGISTRATION_URL}/api/create',
  code: 'ERR_INVALID_URL'
}
```

**Comment by thehabes** [comment]
Ok, then all lines like `const queryURL = '${process.env.RERUM_API_ADDR}${process.env.CREATE}'` will need changed to stop looking in the .env for those.

**Comment by cubap** [comment]
That's right. I think we wandered past that in the standup

**Comment by thehabes** [comment]
We did all of this.

**Pull request closed without merging**
