### PR TITLE
un-got

### LINKED ISSUE #44: Refactor `got()` for `fetch()`

### PR DESCRIPTION
**Pull request by cubap**
mostly changed json to body in the requests and added the method option where needed.

### CODE REVIEW

**Review by thehabes — CHANGES_REQUESTED** [review]
I am unable to `/create` on localhost on the `44-refactor-got-for-fetch` branch.  I am using a fresh copy of the `.env` for tiny-node from dev.

image




> Confirmed I do not experience this behavior when I use the `main` branch.

image

**Comment by cubap** [comment]
> I am unable to `/create` on localhost on the `44-refactor-got-for-fetch` branch. I am using a fresh copy of the `.env` for tiny-node from dev.
> 
> image
> 
> > Confirmed I do not experience this behavior when I use the `main` branch.
> 
> image

Can you confirm this works on https://tinydev.rerum.io right now /create? The error is nonsense, so far as I see. fetchResponse.json() is a thing. I'll switch in and confirm. I can move it inside of a then, if needed, but it is valid and works locally for me and on dev (which I think has the deploy from the PR)

**Comment by cubap** [comment]
Okay, @thehabes I have changed the await to explicitly pass the response into the .json() function in case its just a my machine vs. yours issue. It now looks like the changes that @jsvoo made in his refactor. All checks passing, still looking good on tinydev

**Review by thehabes — CHANGES_REQUESTED** [review]
This did not function.  I was unable to update an object I had just created.  https://devstore.rerum.io/v1/id/66228fd85cc3848690279e96

image

Confirmed functional in production.  https://store.rerum.io/v1/id/6622912ae0b3a85c442f2a8e

image

**Comment by cubap** [comment]
I see the problem. It's outside of my code, but I can fix it. I'm not certain what version is working right now...

**Comment by cubap** [comment]
https://devstore.rerum.io/v1/id/66228fd85cc3848690279e96

**Comment by cubap** [comment]
image

**Review by thehabes — CHANGES_REQUESTED** [review]
I was unable to overwrite an object I had just created.

image

I confirmed this is functional in production
image

**Review by thehabes — APPROVED** [review]
Looks good, I don't see anything extra or wrong in the code.  I tested each endpoint in the browser and through Talend API and everything worked as expected.

Outside of your scope (while I was testing) I noticed we don't exactly have the HTTP responses how we would like for REST.  One blatant example is that I did a PUT request to the /query endpoint which failed as you know it would, but because of a `404` instead of a `405`.  I made https://github.com/CenterForDigitalHumanities/TinyNode/issues/72 for this.

**Pull request merged**
